name: Run Tests

on: [push, pull_request]

env:
  PYTHON_VERSION: "3.10.12"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest

  eval-check:
    name: Run Eval and Check for Changes
    runs-on: ubuntu-latest
    if: false # Isn't deterministic, maybe we need to compare against hte raw data instead of png
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          python -m pip install -e .

      - name: Run eval script
        run: python3.10 src/evals/eval.py

      - name: Check for modified files
        run: |
          git status --porcelain
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "❌ Files were modified after eval. Please run the script locally and commit the results."
            git diff
            exit 1
          fi
